// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.13.0
// source: api/weight/weight.proto

package weight

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 记录体重请求
type RecordWeightRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 时间戳
	Date uint64 `protobuf:"varint,1,opt,name=date,proto3" json:"date,omitempty"`
	// 体重
	Weight float32 `protobuf:"fixed32,2,opt,name=weight,proto3" json:"weight,omitempty"`
	// 图片
	Img string `protobuf:"bytes,3,opt,name=img,proto3" json:"img,omitempty"`
}

func (x *RecordWeightRequest) Reset() {
	*x = RecordWeightRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_weight_weight_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordWeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordWeightRequest) ProtoMessage() {}

func (x *RecordWeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_weight_weight_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordWeightRequest.ProtoReflect.Descriptor instead.
func (*RecordWeightRequest) Descriptor() ([]byte, []int) {
	return file_api_weight_weight_proto_rawDescGZIP(), []int{0}
}

func (x *RecordWeightRequest) GetDate() uint64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *RecordWeightRequest) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *RecordWeightRequest) GetImg() string {
	if x != nil {
		return x.Img
	}
	return ""
}

// 记录体重响应
type RecordWeightReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *RecordWeightReply) Reset() {
	*x = RecordWeightReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_weight_weight_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordWeightReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordWeightReply) ProtoMessage() {}

func (x *RecordWeightReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_weight_weight_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordWeightReply.ProtoReflect.Descriptor instead.
func (*RecordWeightReply) Descriptor() ([]byte, []int) {
	return file_api_weight_weight_proto_rawDescGZIP(), []int{1}
}

func (x *RecordWeightReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RecordWeightReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

//
type GetRecentWeightRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 最近多少天, 默认720天, 最大 365*5
	Latest int32 `protobuf:"varint,1,opt,name=latest,proto3" json:"latest,omitempty"`
}

func (x *GetRecentWeightRequest) Reset() {
	*x = GetRecentWeightRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_weight_weight_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecentWeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentWeightRequest) ProtoMessage() {}

func (x *GetRecentWeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_weight_weight_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentWeightRequest.ProtoReflect.Descriptor instead.
func (*GetRecentWeightRequest) Descriptor() ([]byte, []int) {
	return file_api_weight_weight_proto_rawDescGZIP(), []int{2}
}

func (x *GetRecentWeightRequest) GetLatest() int32 {
	if x != nil {
		return x.Latest
	}
	return 0
}

//
type GetRecentWeightReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32                `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string               `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *GetRecentWeightData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetRecentWeightReply) Reset() {
	*x = GetRecentWeightReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_weight_weight_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecentWeightReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentWeightReply) ProtoMessage() {}

func (x *GetRecentWeightReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_weight_weight_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentWeightReply.ProtoReflect.Descriptor instead.
func (*GetRecentWeightReply) Descriptor() ([]byte, []int) {
	return file_api_weight_weight_proto_rawDescGZIP(), []int{3}
}

func (x *GetRecentWeightReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetRecentWeightReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetRecentWeightReply) GetData() *GetRecentWeightData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetRecentWeightData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total uint64          `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*WeightEntity `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *GetRecentWeightData) Reset() {
	*x = GetRecentWeightData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_weight_weight_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecentWeightData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentWeightData) ProtoMessage() {}

func (x *GetRecentWeightData) ProtoReflect() protoreflect.Message {
	mi := &file_api_weight_weight_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentWeightData.ProtoReflect.Descriptor instead.
func (*GetRecentWeightData) Descriptor() ([]byte, []int) {
	return file_api_weight_weight_proto_rawDescGZIP(), []int{4}
}

func (x *GetRecentWeightData) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetRecentWeightData) GetList() []*WeightEntity {
	if x != nil {
		return x.List
	}
	return nil
}

type WeightEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 日期
	Date string `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	// 体重值
	Weight float32 `protobuf:"fixed32,3,opt,name=weight,proto3" json:"weight,omitempty"`
	// uid
	Uid uint64 `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *WeightEntity) Reset() {
	*x = WeightEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_weight_weight_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeightEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeightEntity) ProtoMessage() {}

func (x *WeightEntity) ProtoReflect() protoreflect.Message {
	mi := &file_api_weight_weight_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeightEntity.ProtoReflect.Descriptor instead.
func (*WeightEntity) Descriptor() ([]byte, []int) {
	return file_api_weight_weight_proto_rawDescGZIP(), []int{5}
}

func (x *WeightEntity) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WeightEntity) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *WeightEntity) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *WeightEntity) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetWeightByMonthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Month string `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
}

func (x *GetWeightByMonthRequest) Reset() {
	*x = GetWeightByMonthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_weight_weight_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWeightByMonthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeightByMonthRequest) ProtoMessage() {}

func (x *GetWeightByMonthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_weight_weight_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeightByMonthRequest.ProtoReflect.Descriptor instead.
func (*GetWeightByMonthRequest) Descriptor() ([]byte, []int) {
	return file_api_weight_weight_proto_rawDescGZIP(), []int{6}
}

func (x *GetWeightByMonthRequest) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

// 当月有体重的数据
type GetWeightByMonthReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32                `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string               `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *GetRecentWeightData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetWeightByMonthReply) Reset() {
	*x = GetWeightByMonthReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_weight_weight_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWeightByMonthReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeightByMonthReply) ProtoMessage() {}

func (x *GetWeightByMonthReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_weight_weight_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeightByMonthReply.ProtoReflect.Descriptor instead.
func (*GetWeightByMonthReply) Descriptor() ([]byte, []int) {
	return file_api_weight_weight_proto_rawDescGZIP(), []int{7}
}

func (x *GetWeightByMonthReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetWeightByMonthReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetWeightByMonthReply) GetData() *GetRecentWeightData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_weight_weight_proto protoreflect.FileDescriptor

var file_api_weight_weight_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x2f, 0x77, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x70, 0x69, 0x2e, 0x77,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x53, 0x0a, 0x13, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x57, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06,
	0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x6d, 0x67, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x6d, 0x67, 0x22, 0x39, 0x0a, 0x11, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0x30, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74,
	0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c,
	0x61, 0x74, 0x65, 0x73, 0x74, 0x22, 0x71, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65,
	0x6e, 0x74, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x12, 0x33, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x59, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x63, 0x65, 0x6e, 0x74, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x2c, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x2e, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x22, 0x5c, 0x0a, 0x0c, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x22, 0x2f, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x42, 0x79,
	0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x6e,
	0x74, 0x68, 0x22, 0x72, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x42,
	0x79, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x12, 0x33, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xe5, 0x02, 0x0a, 0x06, 0x57, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x69, 0x0a, 0x0c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x57, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x2e,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x22, 0x0e, 0x2f, 0x77, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x3a, 0x01, 0x2a, 0x12, 0x75, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12,
	0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x16, 0x12, 0x11, 0x2f,
	0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x2f, 0x67, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74,
	0x3a, 0x01, 0x2a, 0x12, 0x79, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x42, 0x79, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x42, 0x79,
	0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x42, 0x79, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x12, 0x12, 0x2f, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x2f, 0x67, 0x65, 0x74, 0x42, 0x79, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x3a, 0x01, 0x2a, 0x42, 0x2f,
	0x0a, 0x0a, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x50, 0x01, 0x5a, 0x1f,
	0x61, 0x70, 0x69, 0x2d, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x2d, 0x67, 0x6f, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x3b, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_weight_weight_proto_rawDescOnce sync.Once
	file_api_weight_weight_proto_rawDescData = file_api_weight_weight_proto_rawDesc
)

func file_api_weight_weight_proto_rawDescGZIP() []byte {
	file_api_weight_weight_proto_rawDescOnce.Do(func() {
		file_api_weight_weight_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_weight_weight_proto_rawDescData)
	})
	return file_api_weight_weight_proto_rawDescData
}

var file_api_weight_weight_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_weight_weight_proto_goTypes = []interface{}{
	(*RecordWeightRequest)(nil),     // 0: api.weight.RecordWeightRequest
	(*RecordWeightReply)(nil),       // 1: api.weight.RecordWeightReply
	(*GetRecentWeightRequest)(nil),  // 2: api.weight.GetRecentWeightRequest
	(*GetRecentWeightReply)(nil),    // 3: api.weight.GetRecentWeightReply
	(*GetRecentWeightData)(nil),     // 4: api.weight.GetRecentWeightData
	(*WeightEntity)(nil),            // 5: api.weight.WeightEntity
	(*GetWeightByMonthRequest)(nil), // 6: api.weight.GetWeightByMonthRequest
	(*GetWeightByMonthReply)(nil),   // 7: api.weight.GetWeightByMonthReply
}
var file_api_weight_weight_proto_depIdxs = []int32{
	4, // 0: api.weight.GetRecentWeightReply.data:type_name -> api.weight.GetRecentWeightData
	5, // 1: api.weight.GetRecentWeightData.list:type_name -> api.weight.WeightEntity
	4, // 2: api.weight.GetWeightByMonthReply.data:type_name -> api.weight.GetRecentWeightData
	0, // 3: api.weight.Weight.RecordWeight:input_type -> api.weight.RecordWeightRequest
	2, // 4: api.weight.Weight.GetRecentWeight:input_type -> api.weight.GetRecentWeightRequest
	6, // 5: api.weight.Weight.GetWeightByMonth:input_type -> api.weight.GetWeightByMonthRequest
	1, // 6: api.weight.Weight.RecordWeight:output_type -> api.weight.RecordWeightReply
	3, // 7: api.weight.Weight.GetRecentWeight:output_type -> api.weight.GetRecentWeightReply
	7, // 8: api.weight.Weight.GetWeightByMonth:output_type -> api.weight.GetWeightByMonthReply
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_weight_weight_proto_init() }
func file_api_weight_weight_proto_init() {
	if File_api_weight_weight_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_weight_weight_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordWeightRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_weight_weight_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordWeightReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_weight_weight_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRecentWeightRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_weight_weight_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRecentWeightReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_weight_weight_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRecentWeightData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_weight_weight_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeightEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_weight_weight_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWeightByMonthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_weight_weight_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWeightByMonthReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_weight_weight_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_weight_weight_proto_goTypes,
		DependencyIndexes: file_api_weight_weight_proto_depIdxs,
		MessageInfos:      file_api_weight_weight_proto_msgTypes,
	}.Build()
	File_api_weight_weight_proto = out.File
	file_api_weight_weight_proto_rawDesc = nil
	file_api_weight_weight_proto_goTypes = nil
	file_api_weight_weight_proto_depIdxs = nil
}
